/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */
var express = require('express');
var session = require('express-session');
var device = require('express-device');
var logger = require('morgan');
var bodyParser = require('body-parser');
var cookieParser = require('cookie-parser');
var path = require('path');
var createError = require('http-errors');

var searchAppAuthorities = require('./swagger/searchAppAuthorities');
var searchAppContact = require('./swagger/searchAppContact');
var searchAppGroupAuthorities = require('./swagger/searchAppGroupAuthorities');
var searchAppGroupMembers = require('./swagger/searchAppGroupMembers');
var searchAppGroups = require('./swagger/searchAppGroups');
var searchAppMenus = require('./swagger/searchAppMenus');
var searchAppMessage = require('./swagger/searchAppMessage');
var searchAppPersistentLogins = require('./swagger/searchAppPersistentLogins');
var searchAppRoom = require('./swagger/searchAppRoom');
var searchAppUsers = require('./swagger/searchAppUsers');
var searchCcontactAll = require('./swagger/searchCcontactAll');
var searchContrDevices = require('./swagger/searchContrDevices');
var searchContrServicesCap = require('./swagger/searchContrServicesCap');
var searchContractAll = require('./swagger/searchContractAll');
var searchContractHistory = require('./swagger/searchContractHistory');
var searchCustomerAll = require('./swagger/searchCustomerAll');
var searchDirectoryNumber = require('./swagger/searchDirectoryNumber');
var searchInfoContrCheck = require('./swagger/searchInfoContrCheck');
var searchInfoContrCombo = require('./swagger/searchInfoContrCombo');
var searchInfoContrText = require('./swagger/searchInfoContrText');
var searchInfoCustCheck = require('./swagger/searchInfoCustCheck');
var searchInfoCustCombo = require('./swagger/searchInfoCustCombo');
var searchInfoCustText = require('./swagger/searchInfoCustText');
var searchOrderhdrAll = require('./swagger/searchOrderhdrAll');
var searchOrdertrailer = require('./swagger/searchOrdertrailer');
var searchPort = require('./swagger/searchPort');
var searchPrServSpcodeHist = require('./swagger/searchPrServSpcodeHist');
var searchPrServStatusHist = require('./swagger/searchPrServStatusHist');
var searchProfileService = require('./swagger/searchProfileService');
var searchStorageMedium = require('./swagger/searchStorageMedium');
var readAppAuthorities = require('./swagger/readAppAuthorities');
var readAppContact = require('./swagger/readAppContact');
var readAppGroupAuthorities = require('./swagger/readAppGroupAuthorities');
var readAppGroupMembers = require('./swagger/readAppGroupMembers');
var readAppGroups = require('./swagger/readAppGroups');
var readAppMenus = require('./swagger/readAppMenus');
var readAppMessage = require('./swagger/readAppMessage');
var readAppPersistentLogins = require('./swagger/readAppPersistentLogins');
var readAppRoom = require('./swagger/readAppRoom');
var readAppUsers = require('./swagger/readAppUsers');
var readCcontactAll = require('./swagger/readCcontactAll');
var readContrDevices = require('./swagger/readContrDevices');
var readContrServicesCap = require('./swagger/readContrServicesCap');
var readContractAll = require('./swagger/readContractAll');
var readContractHistory = require('./swagger/readContractHistory');
var readCustomerAll = require('./swagger/readCustomerAll');
var readDirectoryNumber = require('./swagger/readDirectoryNumber');
var readInfoContrCheck = require('./swagger/readInfoContrCheck');
var readInfoContrCombo = require('./swagger/readInfoContrCombo');
var readInfoContrText = require('./swagger/readInfoContrText');
var readInfoCustCheck = require('./swagger/readInfoCustCheck');
var readInfoCustCombo = require('./swagger/readInfoCustCombo');
var readInfoCustText = require('./swagger/readInfoCustText');
var readOrderhdrAll = require('./swagger/readOrderhdrAll');
var readOrdertrailer = require('./swagger/readOrdertrailer');
var readPort = require('./swagger/readPort');
var readPrServSpcodeHist = require('./swagger/readPrServSpcodeHist');
var readPrServStatusHist = require('./swagger/readPrServStatusHist');
var readProfileService = require('./swagger/readProfileService');
var readStorageMedium = require('./swagger/readStorageMedium');
var newAppAuthorities = require('./swagger/newAppAuthorities');
var newAppContact = require('./swagger/newAppContact');
var newAppGroupAuthorities = require('./swagger/newAppGroupAuthorities');
var newAppGroupMembers = require('./swagger/newAppGroupMembers');
var newAppGroups = require('./swagger/newAppGroups');
var newAppMenus = require('./swagger/newAppMenus');
var newAppMessage = require('./swagger/newAppMessage');
var newAppPersistentLogins = require('./swagger/newAppPersistentLogins');
var newAppRoom = require('./swagger/newAppRoom');
var newAppUsers = require('./swagger/newAppUsers');
var newCcontactAll = require('./swagger/newCcontactAll');
var newContrDevices = require('./swagger/newContrDevices');
var newContrServicesCap = require('./swagger/newContrServicesCap');
var newContractAll = require('./swagger/newContractAll');
var newContractHistory = require('./swagger/newContractHistory');
var newCustomerAll = require('./swagger/newCustomerAll');
var newDirectoryNumber = require('./swagger/newDirectoryNumber');
var newInfoContrCheck = require('./swagger/newInfoContrCheck');
var newInfoContrCombo = require('./swagger/newInfoContrCombo');
var newInfoContrText = require('./swagger/newInfoContrText');
var newInfoCustCheck = require('./swagger/newInfoCustCheck');
var newInfoCustCombo = require('./swagger/newInfoCustCombo');
var newInfoCustText = require('./swagger/newInfoCustText');
var newOrderhdrAll = require('./swagger/newOrderhdrAll');
var newOrdertrailer = require('./swagger/newOrdertrailer');
var newPort = require('./swagger/newPort');
var newPrServSpcodeHist = require('./swagger/newPrServSpcodeHist');
var newPrServStatusHist = require('./swagger/newPrServStatusHist');
var newProfileService = require('./swagger/newProfileService');
var newStorageMedium = require('./swagger/newStorageMedium');
var writeAppAuthorities = require('./swagger/writeAppAuthorities');
var writeAppContact = require('./swagger/writeAppContact');
var writeAppGroupAuthorities = require('./swagger/writeAppGroupAuthorities');
var writeAppGroupMembers = require('./swagger/writeAppGroupMembers');
var writeAppGroups = require('./swagger/writeAppGroups');
var writeAppMenus = require('./swagger/writeAppMenus');
var writeAppMessage = require('./swagger/writeAppMessage');
var writeAppPersistentLogins = require('./swagger/writeAppPersistentLogins');
var writeAppRoom = require('./swagger/writeAppRoom');
var writeAppUsers = require('./swagger/writeAppUsers');
var writeCcontactAll = require('./swagger/writeCcontactAll');
var writeContrDevices = require('./swagger/writeContrDevices');
var writeContrServicesCap = require('./swagger/writeContrServicesCap');
var writeContractAll = require('./swagger/writeContractAll');
var writeContractHistory = require('./swagger/writeContractHistory');
var writeCustomerAll = require('./swagger/writeCustomerAll');
var writeDirectoryNumber = require('./swagger/writeDirectoryNumber');
var writeInfoContrCheck = require('./swagger/writeInfoContrCheck');
var writeInfoContrCombo = require('./swagger/writeInfoContrCombo');
var writeInfoContrText = require('./swagger/writeInfoContrText');
var writeInfoCustCheck = require('./swagger/writeInfoCustCheck');
var writeInfoCustCombo = require('./swagger/writeInfoCustCombo');
var writeInfoCustText = require('./swagger/writeInfoCustText');
var writeOrderhdrAll = require('./swagger/writeOrderhdrAll');
var writeOrdertrailer = require('./swagger/writeOrdertrailer');
var writePort = require('./swagger/writePort');
var writePrServSpcodeHist = require('./swagger/writePrServSpcodeHist');
var writePrServStatusHist = require('./swagger/writePrServStatusHist');
var writeProfileService = require('./swagger/writeProfileService');
var writeStorageMedium = require('./swagger/writeStorageMedium');
var deleteAppAuthorities = require('./swagger/deleteAppAuthorities');
var deleteAppContact = require('./swagger/deleteAppContact');
var deleteAppGroupAuthorities = require('./swagger/deleteAppGroupAuthorities');
var deleteAppGroupMembers = require('./swagger/deleteAppGroupMembers');
var deleteAppGroups = require('./swagger/deleteAppGroups');
var deleteAppMenus = require('./swagger/deleteAppMenus');
var deleteAppMessage = require('./swagger/deleteAppMessage');
var deleteAppPersistentLogins = require('./swagger/deleteAppPersistentLogins');
var deleteAppRoom = require('./swagger/deleteAppRoom');
var deleteAppUsers = require('./swagger/deleteAppUsers');
var deleteCcontactAll = require('./swagger/deleteCcontactAll');
var deleteContrDevices = require('./swagger/deleteContrDevices');
var deleteContrServicesCap = require('./swagger/deleteContrServicesCap');
var deleteContractAll = require('./swagger/deleteContractAll');
var deleteContractHistory = require('./swagger/deleteContractHistory');
var deleteCustomerAll = require('./swagger/deleteCustomerAll');
var deleteDirectoryNumber = require('./swagger/deleteDirectoryNumber');
var deleteInfoContrCheck = require('./swagger/deleteInfoContrCheck');
var deleteInfoContrCombo = require('./swagger/deleteInfoContrCombo');
var deleteInfoContrText = require('./swagger/deleteInfoContrText');
var deleteInfoCustCheck = require('./swagger/deleteInfoCustCheck');
var deleteInfoCustCombo = require('./swagger/deleteInfoCustCombo');
var deleteInfoCustText = require('./swagger/deleteInfoCustText');
var deleteOrderhdrAll = require('./swagger/deleteOrderhdrAll');
var deleteOrdertrailer = require('./swagger/deleteOrdertrailer');
var deletePort = require('./swagger/deletePort');
var deletePrServSpcodeHist = require('./swagger/deletePrServSpcodeHist');
var deletePrServStatusHist = require('./swagger/deletePrServStatusHist');
var deleteProfileService = require('./swagger/deleteProfileService');
var deleteStorageMedium = require('./swagger/deleteStorageMedium');

var domain = 'domain.com';
var app = express();

app.use(session({
    key: 'client_sid',
    secret: 'secret',
    resave: false,
    saveUninitialized: true,
    cookie: {
        expires: 60000
    }  
}));

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(logger('dev'));
app.use(cookieParser());
app.use(device.capture());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended : true}));

app.use(express.static(path.join(__dirname, 'public_api')));

app.use((req, res, next) => {
  req.session.domain = domain;
  if (req.cookies.user_sid && !req.session.user_sid) {
      res.clearCookie('client_sid');        
  }
  next();
});

app.use('/searchAppAuthorities', searchAppAuthorities);
app.use('/searchAppContact', searchAppContact);
app.use('/searchAppGroupAuthorities', searchAppGroupAuthorities);
app.use('/searchAppGroupMembers', searchAppGroupMembers);
app.use('/searchAppGroups', searchAppGroups);
app.use('/searchAppMenus', searchAppMenus);
app.use('/searchAppMessage', searchAppMessage);
app.use('/searchAppPersistentLogins', searchAppPersistentLogins);
app.use('/searchAppRoom', searchAppRoom);
app.use('/searchAppUsers', searchAppUsers);
app.use('/searchCcontactAll', searchCcontactAll);
app.use('/searchContrDevices', searchContrDevices);
app.use('/searchContrServicesCap', searchContrServicesCap);
app.use('/searchContractAll', searchContractAll);
app.use('/searchContractHistory', searchContractHistory);
app.use('/searchCustomerAll', searchCustomerAll);
app.use('/searchDirectoryNumber', searchDirectoryNumber);
app.use('/searchInfoContrCheck', searchInfoContrCheck);
app.use('/searchInfoContrCombo', searchInfoContrCombo);
app.use('/searchInfoContrText', searchInfoContrText);
app.use('/searchInfoCustCheck', searchInfoCustCheck);
app.use('/searchInfoCustCombo', searchInfoCustCombo);
app.use('/searchInfoCustText', searchInfoCustText);
app.use('/searchOrderhdrAll', searchOrderhdrAll);
app.use('/searchOrdertrailer', searchOrdertrailer);
app.use('/searchPort', searchPort);
app.use('/searchPrServSpcodeHist', searchPrServSpcodeHist);
app.use('/searchPrServStatusHist', searchPrServStatusHist);
app.use('/searchProfileService', searchProfileService);
app.use('/searchStorageMedium', searchStorageMedium);
app.use('/readAppAuthorities', readAppAuthorities);
app.use('/readAppContact', readAppContact);
app.use('/readAppGroupAuthorities', readAppGroupAuthorities);
app.use('/readAppGroupMembers', readAppGroupMembers);
app.use('/readAppGroups', readAppGroups);
app.use('/readAppMenus', readAppMenus);
app.use('/readAppMessage', readAppMessage);
app.use('/readAppPersistentLogins', readAppPersistentLogins);
app.use('/readAppRoom', readAppRoom);
app.use('/readAppUsers', readAppUsers);
app.use('/readCcontactAll', readCcontactAll);
app.use('/readContrDevices', readContrDevices);
app.use('/readContrServicesCap', readContrServicesCap);
app.use('/readContractAll', readContractAll);
app.use('/readContractHistory', readContractHistory);
app.use('/readCustomerAll', readCustomerAll);
app.use('/readDirectoryNumber', readDirectoryNumber);
app.use('/readInfoContrCheck', readInfoContrCheck);
app.use('/readInfoContrCombo', readInfoContrCombo);
app.use('/readInfoContrText', readInfoContrText);
app.use('/readInfoCustCheck', readInfoCustCheck);
app.use('/readInfoCustCombo', readInfoCustCombo);
app.use('/readInfoCustText', readInfoCustText);
app.use('/readOrderhdrAll', readOrderhdrAll);
app.use('/readOrdertrailer', readOrdertrailer);
app.use('/readPort', readPort);
app.use('/readPrServSpcodeHist', readPrServSpcodeHist);
app.use('/readPrServStatusHist', readPrServStatusHist);
app.use('/readProfileService', readProfileService);
app.use('/readStorageMedium', readStorageMedium);
app.use('/newAppAuthorities', newAppAuthorities);
app.use('/newAppContact', newAppContact);
app.use('/newAppGroupAuthorities', newAppGroupAuthorities);
app.use('/newAppGroupMembers', newAppGroupMembers);
app.use('/newAppGroups', newAppGroups);
app.use('/newAppMenus', newAppMenus);
app.use('/newAppMessage', newAppMessage);
app.use('/newAppPersistentLogins', newAppPersistentLogins);
app.use('/newAppRoom', newAppRoom);
app.use('/newAppUsers', newAppUsers);
app.use('/newCcontactAll', newCcontactAll);
app.use('/newContrDevices', newContrDevices);
app.use('/newContrServicesCap', newContrServicesCap);
app.use('/newContractAll', newContractAll);
app.use('/newContractHistory', newContractHistory);
app.use('/newCustomerAll', newCustomerAll);
app.use('/newDirectoryNumber', newDirectoryNumber);
app.use('/newInfoContrCheck', newInfoContrCheck);
app.use('/newInfoContrCombo', newInfoContrCombo);
app.use('/newInfoContrText', newInfoContrText);
app.use('/newInfoCustCheck', newInfoCustCheck);
app.use('/newInfoCustCombo', newInfoCustCombo);
app.use('/newInfoCustText', newInfoCustText);
app.use('/newOrderhdrAll', newOrderhdrAll);
app.use('/newOrdertrailer', newOrdertrailer);
app.use('/newPort', newPort);
app.use('/newPrServSpcodeHist', newPrServSpcodeHist);
app.use('/newPrServStatusHist', newPrServStatusHist);
app.use('/newProfileService', newProfileService);
app.use('/newStorageMedium', newStorageMedium);
app.use('/writeAppAuthorities', writeAppAuthorities);
app.use('/writeAppContact', writeAppContact);
app.use('/writeAppGroupAuthorities', writeAppGroupAuthorities);
app.use('/writeAppGroupMembers', writeAppGroupMembers);
app.use('/writeAppGroups', writeAppGroups);
app.use('/writeAppMenus', writeAppMenus);
app.use('/writeAppMessage', writeAppMessage);
app.use('/writeAppPersistentLogins', writeAppPersistentLogins);
app.use('/writeAppRoom', writeAppRoom);
app.use('/writeAppUsers', writeAppUsers);
app.use('/writeCcontactAll', writeCcontactAll);
app.use('/writeContrDevices', writeContrDevices);
app.use('/writeContrServicesCap', writeContrServicesCap);
app.use('/writeContractAll', writeContractAll);
app.use('/writeContractHistory', writeContractHistory);
app.use('/writeCustomerAll', writeCustomerAll);
app.use('/writeDirectoryNumber', writeDirectoryNumber);
app.use('/writeInfoContrCheck', writeInfoContrCheck);
app.use('/writeInfoContrCombo', writeInfoContrCombo);
app.use('/writeInfoContrText', writeInfoContrText);
app.use('/writeInfoCustCheck', writeInfoCustCheck);
app.use('/writeInfoCustCombo', writeInfoCustCombo);
app.use('/writeInfoCustText', writeInfoCustText);
app.use('/writeOrderhdrAll', writeOrderhdrAll);
app.use('/writeOrdertrailer', writeOrdertrailer);
app.use('/writePort', writePort);
app.use('/writePrServSpcodeHist', writePrServSpcodeHist);
app.use('/writePrServStatusHist', writePrServStatusHist);
app.use('/writeProfileService', writeProfileService);
app.use('/writeStorageMedium', writeStorageMedium);
app.use('/deleteAppAuthorities', deleteAppAuthorities);
app.use('/deleteAppContact', deleteAppContact);
app.use('/deleteAppGroupAuthorities', deleteAppGroupAuthorities);
app.use('/deleteAppGroupMembers', deleteAppGroupMembers);
app.use('/deleteAppGroups', deleteAppGroups);
app.use('/deleteAppMenus', deleteAppMenus);
app.use('/deleteAppMessage', deleteAppMessage);
app.use('/deleteAppPersistentLogins', deleteAppPersistentLogins);
app.use('/deleteAppRoom', deleteAppRoom);
app.use('/deleteAppUsers', deleteAppUsers);
app.use('/deleteCcontactAll', deleteCcontactAll);
app.use('/deleteContrDevices', deleteContrDevices);
app.use('/deleteContrServicesCap', deleteContrServicesCap);
app.use('/deleteContractAll', deleteContractAll);
app.use('/deleteContractHistory', deleteContractHistory);
app.use('/deleteCustomerAll', deleteCustomerAll);
app.use('/deleteDirectoryNumber', deleteDirectoryNumber);
app.use('/deleteInfoContrCheck', deleteInfoContrCheck);
app.use('/deleteInfoContrCombo', deleteInfoContrCombo);
app.use('/deleteInfoContrText', deleteInfoContrText);
app.use('/deleteInfoCustCheck', deleteInfoCustCheck);
app.use('/deleteInfoCustCombo', deleteInfoCustCombo);
app.use('/deleteInfoCustText', deleteInfoCustText);
app.use('/deleteOrderhdrAll', deleteOrderhdrAll);
app.use('/deleteOrdertrailer', deleteOrdertrailer);
app.use('/deletePort', deletePort);
app.use('/deletePrServSpcodeHist', deletePrServSpcodeHist);
app.use('/deletePrServStatusHist', deletePrServStatusHist);
app.use('/deleteProfileService', deleteProfileService);
app.use('/deleteStorageMedium', deleteStorageMedium);

var swaggerUi = require('swagger-ui-express');
var swaggerJSDoc = require('swagger-jsdoc');

const swaggerDefinition = {
  info: {
    title: 'Micro Service Swagger API',
    version: '1.0.0',
    description: 'Endpoints to user administration routes',
  },
  host: 'localhost:3001',
  basePath: '/',
  securityDefinitions: {
    bearerAuth: {
      type: 'apiKey',
      name: 'Authorization',
      scheme: 'bearer',
      in: 'header',
    },
  },
};

const options = {
  swaggerDefinition,
  apis: ['./swagger/*.js'],
};

const swaggerSpec = swaggerJSDoc(options);
app.use('/swagger.json', (req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.send(swaggerSpec);
});

var optionSpec = {
  customCss: '.swagger-ui .opblock .opblock-summary-description {text-align: right;padding-right: 20px;}'
};
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec,optionSpec));

module.exports = app;
