/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /readContractAll:
 *   get:
 *     tags:
 *       - Administration
 *     description: readContractAll
 *     summary: ContractAllRead
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: coId
 *         description: Integer 
 *         in: query
 *         type: Integer
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    
    var readContractAll = new Promise((resolve, reject) => {
        dao.readContractAll(jsonObj,function(err,rows) {
            if(err) res.status(err.code).end();
            else{
                if(rows[0]===undefined) res.status(404).end();
                else{ 
                    jsonObj = rows[0];
                    resolve(jsonObj);
                }
            }
        });
    });
    
    var contrDevices = new Promise((resolve, reject) => {
        dao.searchContrDevices(jsonObj,function(err,rows) {
            jsonObj.contrDevices = rows;
            resolve(jsonObj);
        });        
    });
    
    var contrServicesCap = new Promise((resolve, reject) => {
        dao.searchContrServicesCap(jsonObj,function(err,rows) {
            jsonObj.contrServicesCap = rows;
            resolve(jsonObj);
        });        
    });
    
    var contractHistory = new Promise((resolve, reject) => {
        dao.searchContractHistory(jsonObj,function(err,rows) {
            jsonObj.contractHistory = rows;
            resolve(jsonObj);
        });        
    });
    
    var infoContrCheck = new Promise((resolve, reject) => {
        dao.searchInfoContrCheck(jsonObj,function(err,rows) {
            jsonObj.infoContrCheck = rows;
            resolve(jsonObj);
        });        
    });
    
    var infoContrCombo = new Promise((resolve, reject) => {
        dao.searchInfoContrCombo(jsonObj,function(err,rows) {
            jsonObj.infoContrCombo = rows;
            resolve(jsonObj);
        });        
    });
    
    var infoContrText = new Promise((resolve, reject) => {
        dao.searchInfoContrText(jsonObj,function(err,rows) {
            jsonObj.infoContrText = rows;
            resolve(jsonObj);
        });        
    });
    
    var profileService = new Promise((resolve, reject) => {
        dao.searchProfileService(jsonObj,function(err,rows) {
            jsonObj.profileService = rows;
            resolve(jsonObj);
        });        
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        res.status(200).send(jsonObj);
    }
    
    Promise.all([readContractAll,contrDevices,contrServicesCap,contractHistory,infoContrCheck,infoContrCombo,infoContrText,profileService]).then(sendResult);
});

module.exports = router;
