/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchContractAll:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchContractAll
 *     summary: ContractAllSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: coId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: customerId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: type
 *         description: String
 *         in: query
 *         type: String
 *       - name: plcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: sccode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: submId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coSigned
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coEquType
 *         description: String
 *         in: query
 *         type: String
 *       - name: coRepBill
 *         description: String
 *         in: query
 *         type: String
 *       - name: coRep
 *         description: String
 *         in: query
 *         type: String
 *       - name: coRepBillIdno
 *         description: String
 *         in: query
 *         type: String
 *       - name: coRepIdno
 *         description: String
 *         in: query
 *         type: String
 *       - name: coInstalled
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coArchive
 *         description: String
 *         in: query
 *         type: String
 *       - name: coDirEntry
 *         description: String
 *         in: query
 *         type: String
 *       - name: coOperatorDir
 *         description: String
 *         in: query
 *         type: String
 *       - name: coPstnDir
 *         description: String
 *         in: query
 *         type: String
 *       - name: coAssServ
 *         description: String
 *         in: query
 *         type: String
 *       - name: coAssEqu
 *         description: String
 *         in: query
 *         type: String
 *       - name: coCrdCheck
 *         description: String
 *         in: query
 *         type: String
 *       - name: coCrdChkEnd
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coCrdChkStart
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coCrdClicks
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coCrdClicksDay
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coCrdDays
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coComment
 *         description: String
 *         in: query
 *         type: String
 *       - name: coReserved
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coExpirDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coActivated
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coEntdate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coModdate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coUserlastmod
 *         description: String
 *         in: query
 *         type: String
 *       - name: tmcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: tmcodeDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coCrdDTr1
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coCrdDTr2
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coCrdDTr3
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coCrdPTr1
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coCrdPTr2
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coCrdPTr3
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: eccodeLdc
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: pendingEccodeLdc
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: eccodeLec
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: pendingEccodeLec
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coRequest
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: dealerId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: notValid
 *         description: String
 *         in: query
 *         type: String
 *       - name: arpcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coAddrOnIbill
 *         description: String
 *         in: query
 *         type: String
 *       - name: coCrdAmount
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: coCrdAmountDay
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: productHistoryDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coConfirm
 *         description: String
 *         in: query
 *         type: String
 *       - name: coExtCsuin
 *         description: String
 *         in: query
 *         type: String
 *       - name: trialEndDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coIbCdrFlag
 *         description: String
 *         in: query
 *         type: String
 *       - name: currency
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: anPackageId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coRelType
 *         description: String
 *         in: query
 *         type: String
 *       - name: pendingTmcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: contractTemplate
 *         description: String
 *         in: query
 *         type: String
 *       - name: coCode
 *         description: String
 *         in: query
 *         type: String
 *       - name: businessUnitId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: description
 *         description: String
 *         in: query
 *         type: String
 *       - name: agreementType
 *         description: String
 *         in: query
 *         type: String
 *       - name: extProductId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: remotePlcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: eccode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: hplmnBidGroupId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: vplmnBidGroupId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: homePartyId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: contractTypeId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: trialStartDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: fohAggregationFlag
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: glAccPackId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: cdsBillMedium
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: cdsGeneration
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: chargePartNum
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: chStatus
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: svpFile
 *         description: String
 *         in: query
 *         type: String
 *       - name: makeCallsDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: coInprepayPending
 *         description: String
 *         in: query
 *         type: String
 *       - name: coInprepay
 *         description: String
 *         in: query
 *         type: String
 *       - name: chargePerAdjRef
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: nextCutoffDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: lastCutoffDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: lastChargeDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: lastNoticeDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: notBillMedium
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: chargeStartDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: earliestEndDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: commonRefDataInd
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: contractLanguage
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: pendingLanguage
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: rrCandidate
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: chStatusValidfrom
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchContractAll(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.contractAll = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
