/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchInfoContrText:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchInfoContrText
 *     summary: InfoContrTextSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: coId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: text01
 *         description: String
 *         in: query
 *         type: String
 *       - name: text02
 *         description: String
 *         in: query
 *         type: String
 *       - name: text03
 *         description: String
 *         in: query
 *         type: String
 *       - name: text04
 *         description: String
 *         in: query
 *         type: String
 *       - name: text05
 *         description: String
 *         in: query
 *         type: String
 *       - name: text06
 *         description: String
 *         in: query
 *         type: String
 *       - name: text07
 *         description: String
 *         in: query
 *         type: String
 *       - name: text08
 *         description: String
 *         in: query
 *         type: String
 *       - name: text09
 *         description: String
 *         in: query
 *         type: String
 *       - name: text10
 *         description: String
 *         in: query
 *         type: String
 *       - name: text11
 *         description: String
 *         in: query
 *         type: String
 *       - name: text12
 *         description: String
 *         in: query
 *         type: String
 *       - name: text13
 *         description: String
 *         in: query
 *         type: String
 *       - name: text14
 *         description: String
 *         in: query
 *         type: String
 *       - name: text15
 *         description: String
 *         in: query
 *         type: String
 *       - name: text16
 *         description: String
 *         in: query
 *         type: String
 *       - name: text17
 *         description: String
 *         in: query
 *         type: String
 *       - name: text18
 *         description: String
 *         in: query
 *         type: String
 *       - name: text19
 *         description: String
 *         in: query
 *         type: String
 *       - name: text20
 *         description: String
 *         in: query
 *         type: String
 *       - name: text21
 *         description: String
 *         in: query
 *         type: String
 *       - name: text22
 *         description: String
 *         in: query
 *         type: String
 *       - name: text23
 *         description: String
 *         in: query
 *         type: String
 *       - name: text24
 *         description: String
 *         in: query
 *         type: String
 *       - name: text25
 *         description: String
 *         in: query
 *         type: String
 *       - name: text26
 *         description: String
 *         in: query
 *         type: String
 *       - name: text27
 *         description: String
 *         in: query
 *         type: String
 *       - name: text28
 *         description: String
 *         in: query
 *         type: String
 *       - name: text29
 *         description: String
 *         in: query
 *         type: String
 *       - name: text30
 *         description: String
 *         in: query
 *         type: String
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchInfoContrText(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.infoContrText = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
