/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchPrServSpcodeHist:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchPrServSpcodeHist
 *     summary: PrServSpcodeHistSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: profileId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: sncode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: histno
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: spcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: transactionno
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: validFromDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: entryDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: requestId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchPrServSpcodeHist(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.prServSpcodeHist = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
