/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchStorageMedium:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchStorageMedium
 *     summary: StorageMediumSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: smId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: plcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: smcId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: smSerialnum
 *         description: String
 *         in: query
 *         type: String
 *       - name: smStatus
 *         description: String
 *         in: query
 *         type: String
 *       - name: smStatusModDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: dealerId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: smDeliveryId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: smDeliveryDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: simpohId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: simpotId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: simpotBatch
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: smPin
 *         description: String
 *         in: query
 *         type: String
 *       - name: smPuk
 *         description: String
 *         in: query
 *         type: String
 *       - name: smAccControl
 *         description: String
 *         in: query
 *         type: String
 *       - name: smCodeAdm
 *         description: String
 *         in: query
 *         type: String
 *       - name: spIdE
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: spIdG
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: smStatusRequ
 *         description: String
 *         in: query
 *         type: String
 *       - name: smStaRequDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: smEntdate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: smModdate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: smUserlastmod
 *         description: String
 *         in: query
 *         type: String
 *       - name: smPin2
 *         description: String
 *         in: query
 *         type: String
 *       - name: smPuk2
 *         description: String
 *         in: query
 *         type: String
 *       - name: smAuth
 *         description: String
 *         in: query
 *         type: String
 *       - name: piId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: externalInd
 *         description: String
 *         in: query
 *         type: String
 *       - name: vendcode
 *         description: String
 *         in: query
 *         type: String
 *       - name: smAdm1
 *         description: String
 *         in: query
 *         type: String
 *       - name: smAdm2
 *         description: String
 *         in: query
 *         type: String
 *       - name: smAdm3
 *         description: String
 *         in: query
 *         type: String
 *       - name: smAdm4
 *         description: String
 *         in: query
 *         type: String
 *       - name: smCodeRetailer
 *         description: String
 *         in: query
 *         type: String
 *       - name: smCodeA
 *         description: String
 *         in: query
 *         type: String
 *       - name: smCodeB
 *         description: String
 *         in: query
 *         type: String
 *       - name: smAuthPending
 *         description: String
 *         in: query
 *         type: String
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: smOrigEsnId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: prepaidProfileId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: raProcessId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: transactionId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: businessUnitId
 *         description: Integer
 *         in: query
 *         type: Integer
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchStorageMedium(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.storageMedium = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
