/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchProfileService:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchProfileService
 *     summary: ProfileServiceSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: profileId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: coId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: sncode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: spcodeHistno
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: statusHistno
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: entryDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: channelNum
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: ovwAccFirst
 *         description: String
 *         in: query
 *         type: String
 *       - name: dateBilled
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: snClass
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: ovwSubscr
 *         description: String
 *         in: query
 *         type: String
 *       - name: subscript
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: ovwAccess
 *         description: String
 *         in: query
 *         type: String
 *       - name: ovwAccPrd
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: accessfee
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: channelExcl
 *         description: String
 *         in: query
 *         type: String
 *       - name: disSubscr
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: installDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: trialEndDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: prmValueId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: currency
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: srvType
 *         description: String
 *         in: query
 *         type: String
 *       - name: srvSubtype
 *         description: String
 *         in: query
 *         type: String
 *       - name: ovwAdvCharge
 *         description: String
 *         in: query
 *         type: String
 *       - name: advCharge
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: advChargePrd
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: deleteFlag
 *         description: String
 *         in: query
 *         type: String
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: attribHistno
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: attribHistnoNnp
 *         description: Integer
 *         in: query
 *         type: Integer
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchProfileService(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.profileService = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
