/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchContrServicesCap:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchContrServicesCap
 *     summary: ContrServicesCapSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: coId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: sncode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: seqno
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: seqnoPre
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: bccode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: pendingBccode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: dnId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: dnBlockId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: mainDirnum
 *         description: String
 *         in: query
 *         type: String
 *       - name: csStatus
 *         description: String
 *         in: query
 *         type: String
 *       - name: csActivDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: csDeactivDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: csRequest
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: publicNumberDnId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: vpnId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: publicBlockId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: profileId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: dnShownInBill
 *         description: String
 *         in: query
 *         type: String
 *       - name: requestId
 *         description: Integer
 *         in: query
 *         type: Integer
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchContrServicesCap(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.contrServicesCap = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
