/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchCustomerAll:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchCustomerAll
 *     summary: CustomerAllSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: customerId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: customerIdHigh
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: custcode
 *         description: String
 *         in: query
 *         type: String
 *       - name: csst
 *         description: String
 *         in: query
 *         type: String
 *       - name: cstype
 *         description: String
 *         in: query
 *         type: String
 *       - name: csactivated
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: csdeactivated
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: cstypeDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: cslevel
 *         description: String
 *         in: query
 *         type: String
 *       - name: cslvlname
 *         description: String
 *         in: query
 *         type: String
 *       - name: tmcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: prgcode
 *         description: String
 *         in: query
 *         type: String
 *       - name: csclimit
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: cscurbalance
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: csdepdate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: cstestbillrun
 *         description: String
 *         in: query
 *         type: String
 *       - name: billLayout
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: paymntresp
 *         description: String
 *         in: query
 *         type: String
 *       - name: targetReached
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: pcsmethpaymnt
 *         description: String
 *         in: query
 *         type: String
 *       - name: dunningFlag
 *         description: String
 *         in: query
 *         type: String
 *       - name: commNo
 *         description: String
 *         in: query
 *         type: String
 *       - name: posCommType
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: btxPassword
 *         description: String
 *         in: query
 *         type: String
 *       - name: btxUser
 *         description: String
 *         in: query
 *         type: String
 *       - name: settlesPMonth
 *         description: String
 *         in: query
 *         type: String
 *       - name: cashretour
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: cstradecode
 *         description: String
 *         in: query
 *         type: String
 *       - name: cspassword
 *         description: String
 *         in: query
 *         type: String
 *       - name: cspromotion
 *         description: String
 *         in: query
 *         type: String
 *       - name: csreason
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: cscollector
 *         description: String
 *         in: query
 *         type: String
 *       - name: cscontresp
 *         description: String
 *         in: query
 *         type: String
 *       - name: csdeposit
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: cscreditDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: cscreditRemark
 *         description: String
 *         in: query
 *         type: String
 *       - name: suspended
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: reactivated
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: prevBalance
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: lbcDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: crlimitExc
 *         description: String
 *         in: query
 *         type: String
 *       - name: areaId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: costcenterId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: csfedtaxid
 *         description: String
 *         in: query
 *         type: String
 *       - name: creditRating
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: cscreditStatus
 *         description: String
 *         in: query
 *         type: String
 *       - name: deactCreateDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: deactReceipDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: edifactAddr
 *         description: String
 *         in: query
 *         type: String
 *       - name: edifactUserFlag
 *         description: String
 *         in: query
 *         type: String
 *       - name: edifactFlag
 *         description: String
 *         in: query
 *         type: String
 *       - name: csdepositDueDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: calculateDeposit
 *         description: String
 *         in: query
 *         type: String
 *       - name: tmcodeDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: csrentalbc
 *         description: String
 *         in: query
 *         type: String
 *       - name: userLastmod
 *         description: String
 *         in: query
 *         type: String
 *       - name: csentdate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: csmoddate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: csmod
 *         description: String
 *         in: query
 *         type: String
 *       - name: customerIdExt
 *         description: String
 *         in: query
 *         type: String
 *       - name: csclimitOTr1
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: csclimitOTr2
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: csclimitOTr3
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: cscreditScore
 *         description: String
 *         in: query
 *         type: String
 *       - name: cstraderef
 *         description: String
 *         in: query
 *         type: String
 *       - name: wpid
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: csprepayment
 *         description: String
 *         in: query
 *         type: String
 *       - name: csremark1
 *         description: String
 *         in: query
 *         type: String
 *       - name: csremark2
 *         description: String
 *         in: query
 *         type: String
 *       - name: billInformation
 *         description: String
 *         in: query
 *         type: String
 *       - name: dealerId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: dunningMode
 *         description: String
 *         in: query
 *         type: String
 *       - name: notValid
 *         description: String
 *         in: query
 *         type: String
 *       - name: cscrdcheckAgreed
 *         description: String
 *         in: query
 *         type: String
 *       - name: expectPayCurrId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: convratetypePayment
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: refundCurrId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: convratetypeRefund
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: srcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: currency
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: anonymousCustomer
 *         description: String
 *         in: query
 *         type: String
 *       - name: externalCustomerId
 *         description: String
 *         in: query
 *         type: String
 *       - name: externalCustomerSetId
 *         description: String
 *         in: query
 *         type: String
 *       - name: custnum
 *         description: String
 *         in: query
 *         type: String
 *       - name: businessUnitId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: partyTypeId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: individualOverdiscFlag
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: billingThreshold
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: billingThresholdCurrency
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: thresholdBillingMode
 *         description: String
 *         in: query
 *         type: String
 *       - name: thresholdBillingPurpose
 *         description: String
 *         in: query
 *         type: String
 *       - name: collectionInd
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: rrCandidate
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: bchLastRunDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: createdByUser
 *         description: String
 *         in: query
 *         type: String
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchCustomerAll(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.customerAll = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
