/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchOrdertrailer:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchOrdertrailer
 *     summary: OrdertrailerSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: otxact
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otseq
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otmeas
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otum
 *         description: String
 *         in: query
 *         type: String
 *       - name: otup
 *         description: String
 *         in: query
 *         type: String
 *       - name: otqord
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otqbkord
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otqtoshp
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otdftprc
 *         description: String
 *         in: query
 *         type: String
 *       - name: otprgroup
 *         description: String
 *         in: query
 *         type: String
 *       - name: otfrtwgt
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otjobcost
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otname
 *         description: String
 *         in: query
 *         type: String
 *       - name: otglsale
 *         description: String
 *         in: query
 *         type: String
 *       - name: otglcogs
 *         description: String
 *         in: query
 *         type: String
 *       - name: otglinv
 *         description: String
 *         in: query
 *         type: String
 *       - name: otqship
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otprmeas
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otprum
 *         description: String
 *         in: query
 *         type: String
 *       - name: otbillunits
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otinvunits
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcostflg
 *         description: String
 *         in: query
 *         type: String
 *       - name: otinvalloc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otshipdate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: sncode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: oteqId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: oteqrate
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otleasing
 *         description: String
 *         in: query
 *         type: String
 *       - name: otleasFinish
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: otflsqn
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otvplmn
 *         description: String
 *         in: query
 *         type: String
 *       - name: otflname
 *         description: String
 *         in: query
 *         type: String
 *       - name: otfct
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: otlct
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: otsimFrom
 *         description: String
 *         in: query
 *         type: String
 *       - name: otsimTo
 *         description: String
 *         in: query
 *         type: String
 *       - name: ottransactionDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: servcatCode
 *         description: String
 *         in: query
 *         type: String
 *       - name: servCode
 *         description: String
 *         in: query
 *         type: String
 *       - name: servType
 *         description: String
 *         in: query
 *         type: String
 *       - name: taxInclusiveInd
 *         description: String
 *         in: query
 *         type: String
 *       - name: otglDisc
 *         description: String
 *         in: query
 *         type: String
 *       - name: otjcidDisc
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otglMincom
 *         description: String
 *         in: query
 *         type: String
 *       - name: otjcidMincom
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: glCurrency
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: documentCurrency
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otamtDiscGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtDiscGrossGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtMincomGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtMincomGrossGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtRevenueGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtRevenueGrossGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtDiscGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtDiscGrossGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtGrossGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtMincomGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtMincomGrossGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtRevenueGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtRevenueGrossGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otmerchGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otmerchGrossGl
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtDiscDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtDiscGrossDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtMincomDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtMincomGrossDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtRevenueDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtRevenueGrossDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtDiscDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtDiscGrossDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtGrossDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtMincomDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtMincomGrossDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtRevenueDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otcuramtRevenueGrossDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otgpriceDisDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otgpriceDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otmerchDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otmerchGrossDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: ottaxExemptedDoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otamtDiscSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtDiscGrossSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtMincomSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtMincomGrossSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtRevenueSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otamtRevenueGrossSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otgpriceSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otgpriceDisSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otmerchSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otmerchGrossSecdoc
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: otflrapflg
 *         description: String
 *         in: query
 *         type: String
 *       - name: tapRefNo
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: taxCalculationType
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: profileId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: paymentOption
 *         description: Boolean
 *         in: query
 *         type: Boolean
 *       - name: bpCoId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otcostcent
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: otordnum
 *         description: String
 *         in: query
 *         type: String
 *       - name: incomingDocTaxItemSeqno
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: tmcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: rateplanVscode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: spcode
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: invoiceItemClassId
 *         description: Integer
 *         in: query
 *         type: Integer
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchOrdertrailer(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.ordertrailer = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
