/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchInfoCustCheck:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchInfoCustCheck
 *     summary: InfoCustCheckSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: customerId
 *         description: Integer
 *         in: query
 *         type: Integer
 *       - name: check01
 *         description: String
 *         in: query
 *         type: String
 *       - name: check02
 *         description: String
 *         in: query
 *         type: String
 *       - name: check03
 *         description: String
 *         in: query
 *         type: String
 *       - name: check04
 *         description: String
 *         in: query
 *         type: String
 *       - name: check05
 *         description: String
 *         in: query
 *         type: String
 *       - name: check06
 *         description: String
 *         in: query
 *         type: String
 *       - name: check07
 *         description: String
 *         in: query
 *         type: String
 *       - name: check08
 *         description: String
 *         in: query
 *         type: String
 *       - name: check09
 *         description: String
 *         in: query
 *         type: String
 *       - name: check10
 *         description: String
 *         in: query
 *         type: String
 *       - name: check11
 *         description: String
 *         in: query
 *         type: String
 *       - name: check12
 *         description: String
 *         in: query
 *         type: String
 *       - name: check13
 *         description: String
 *         in: query
 *         type: String
 *       - name: check14
 *         description: String
 *         in: query
 *         type: String
 *       - name: check15
 *         description: String
 *         in: query
 *         type: String
 *       - name: check16
 *         description: String
 *         in: query
 *         type: String
 *       - name: check17
 *         description: String
 *         in: query
 *         type: String
 *       - name: check18
 *         description: String
 *         in: query
 *         type: String
 *       - name: check19
 *         description: String
 *         in: query
 *         type: String
 *       - name: check20
 *         description: String
 *         in: query
 *         type: String
 *       - name: recVersion
 *         description: Integer
 *         in: query
 *         type: Integer
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchInfoCustCheck(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.infoCustCheck = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
