/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'CcontactAllDelete',
    Heading:'CcontactAll',
    CustomerId:{label :'CustomerId'},
    Ccseq:{label :'Ccseq'},
    Cctitle:{label :'Cctitle'},
    Ccname:{label :'Ccname'},
    Ccfname:{label :'Ccfname'},
    Cclname:{label :'Cclname'},
    Ccstreet:{label :'Ccstreet'},
    Ccstreetno:{label :'Ccstreetno'},
    Cclnamemc:{label :'Cclnamemc'},
    Ccaddr1:{label :'Ccaddr1'},
    Ccaddr2:{label :'Ccaddr2'},
    Ccaddr3:{label :'Ccaddr3'},
    Cccity:{label :'Cccity'},
    Cczip:{label :'Cczip'},
    Cctn:{label :'Cctn'},
    Cctn2:{label :'Cctn2'},
    Ccfax:{label :'Ccfax'},
    Ccline1:{label :'Ccline1'},
    Ccline2:{label :'Ccline2'},
    Ccline3:{label :'Ccline3'},
    Ccline4:{label :'Ccline4'},
    Ccline5:{label :'Ccline5'},
    Ccline6:{label :'Ccline6'},
    CctnArea:{label :'CctnArea'},
    Cctn2Area:{label :'Cctn2Area'},
    CcfaxArea:{label :'CcfaxArea'},
    Ccjobdesc:{label :'Ccjobdesc'},
    Ccdeftrk:{label :'Ccdeftrk'},
    Ccuser:{label :'Ccuser'},
    Ccbill:{label :'Ccbill'},
    Ccbilldetails:{label :'Ccbilldetails'},
    Cccontract:{label :'Cccontract'},
    Ccship:{label :'Ccship'},
    Ccmagazine:{label :'Ccmagazine'},
    Ccdirectory:{label :'Ccdirectory'},
    Ccforward:{label :'Ccforward'},
    Ccurgent:{label :'Ccurgent'},
    Country:{label :'Country'},
    Cclanguage:{label :'Cclanguage'},
    Ccadditional:{label :'Ccadditional'},
    SortCriteria:{label :'SortCriteria'},
    Ccentdate:{label :'Ccentdate'},
    Ccmoddate:{label :'Ccmoddate'},
    Ccmod:{label :'Ccmod'},
    Cccounty:{label :'Cccounty'},
    Ccstate:{label :'Ccstate'},
    Ccvaliddate:{label :'Ccvaliddate'},
    CcbillPrevious:{label :'CcbillPrevious'},
    WelcomeCrit:{label :'WelcomeCrit'},
    Ccmname:{label :'Ccmname'},
    Ccemail:{label :'Ccemail'},
    Ccaddryears:{label :'Ccaddryears'},
    Ccsmsno:{label :'Ccsmsno'},
    Ccbilltemp:{label :'Ccbilltemp'},
    Userlastmod:{label :'Userlastmod'},
    Ccvalidation:{label :'Ccvalidation'},
    CcuserInst:{label :'CcuserInst'},
    Cclocation1:{label :'Cclocation1'},
    Cclocation2:{label :'Cclocation2'},
    Ccremark:{label :'Ccremark'},
    RecVersion:{label :'RecVersion'},
    MaritalStatus:{label :'MaritalStatus'},
    Csnationality:{label :'Csnationality'},
    Cssocialsecno:{label :'Cssocialsecno'},
    Csdrivelicence:{label :'Csdrivelicence'},
    Csemployer:{label :'Csemployer'},
    Employee:{label :'Employee'},
    CompanyType:{label :'CompanyType'},
    IdType:{label :'IdType'},
    Passportno:{label :'Passportno'},
    Birthdate:{label :'Birthdate'},
    Cscompregno:{label :'Cscompregno'},
    Cscomptaxno:{label :'Cscomptaxno'},
    Cscusttype:{label :'Cscusttype'},
    Ccsex:{label :'Ccsex'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteCcontactAll(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
