/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ContractAllDelete',
    Heading:'ContractAll',
    CoId:{label :'CoId'},
    CustomerId:{label :'CustomerId'},
    Type:{label :'Type'},
    Plcode:{label :'Plcode'},
    Sccode:{label :'Sccode'},
    SubmId:{label :'SubmId'},
    CoSigned:{label :'CoSigned'},
    CoEquType:{label :'CoEquType'},
    CoRepBill:{label :'CoRepBill'},
    CoRep:{label :'CoRep'},
    CoRepBillIdno:{label :'CoRepBillIdno'},
    CoRepIdno:{label :'CoRepIdno'},
    CoInstalled:{label :'CoInstalled'},
    CoArchive:{label :'CoArchive'},
    CoDirEntry:{label :'CoDirEntry'},
    CoOperatorDir:{label :'CoOperatorDir'},
    CoPstnDir:{label :'CoPstnDir'},
    CoAssServ:{label :'CoAssServ'},
    CoAssEqu:{label :'CoAssEqu'},
    CoCrdCheck:{label :'CoCrdCheck'},
    CoCrdChkEnd:{label :'CoCrdChkEnd'},
    CoCrdChkStart:{label :'CoCrdChkStart'},
    CoCrdClicks:{label :'CoCrdClicks'},
    CoCrdClicksDay:{label :'CoCrdClicksDay'},
    CoCrdDays:{label :'CoCrdDays'},
    CoComment:{label :'CoComment'},
    CoReserved:{label :'CoReserved'},
    CoExpirDate:{label :'CoExpirDate'},
    CoActivated:{label :'CoActivated'},
    CoEntdate:{label :'CoEntdate'},
    CoModdate:{label :'CoModdate'},
    CoUserlastmod:{label :'CoUserlastmod'},
    Tmcode:{label :'Tmcode'},
    TmcodeDate:{label :'TmcodeDate'},
    CoCrdDTr1:{label :'CoCrdDTr1'},
    CoCrdDTr2:{label :'CoCrdDTr2'},
    CoCrdDTr3:{label :'CoCrdDTr3'},
    CoCrdPTr1:{label :'CoCrdPTr1'},
    CoCrdPTr2:{label :'CoCrdPTr2'},
    CoCrdPTr3:{label :'CoCrdPTr3'},
    EccodeLdc:{label :'EccodeLdc'},
    PendingEccodeLdc:{label :'PendingEccodeLdc'},
    EccodeLec:{label :'EccodeLec'},
    PendingEccodeLec:{label :'PendingEccodeLec'},
    CoRequest:{label :'CoRequest'},
    DealerId:{label :'DealerId'},
    NotValid:{label :'NotValid'},
    Arpcode:{label :'Arpcode'},
    CoAddrOnIbill:{label :'CoAddrOnIbill'},
    CoCrdAmount:{label :'CoCrdAmount'},
    CoCrdAmountDay:{label :'CoCrdAmountDay'},
    ProductHistoryDate:{label :'ProductHistoryDate'},
    CoConfirm:{label :'CoConfirm'},
    CoExtCsuin:{label :'CoExtCsuin'},
    TrialEndDate:{label :'TrialEndDate'},
    CoIbCdrFlag:{label :'CoIbCdrFlag'},
    Currency:{label :'Currency'},
    RecVersion:{label :'RecVersion'},
    AnPackageId:{label :'AnPackageId'},
    CoRelType:{label :'CoRelType'},
    PendingTmcode:{label :'PendingTmcode'},
    ContractTemplate:{label :'ContractTemplate'},
    CoCode:{label :'CoCode'},
    BusinessUnitId:{label :'BusinessUnitId'},
    Description:{label :'Description'},
    AgreementType:{label :'AgreementType'},
    ExtProductId:{label :'ExtProductId'},
    RemotePlcode:{label :'RemotePlcode'},
    Eccode:{label :'Eccode'},
    HplmnBidGroupId:{label :'HplmnBidGroupId'},
    VplmnBidGroupId:{label :'VplmnBidGroupId'},
    HomePartyId:{label :'HomePartyId'},
    ContractTypeId:{label :'ContractTypeId'},
    TrialStartDate:{label :'TrialStartDate'},
    FohAggregationFlag:{label :'FohAggregationFlag'},
    GlAccPackId:{label :'GlAccPackId'},
    CdsBillMedium:{label :'CdsBillMedium'},
    CdsGeneration:{label :'CdsGeneration'},
    ChargePartNum:{label :'ChargePartNum'},
    ChStatus:{label :'ChStatus'},
    SvpFile:{label :'SvpFile'},
    MakeCallsDate:{label :'MakeCallsDate'},
    CoInprepayPending:{label :'CoInprepayPending'},
    CoInprepay:{label :'CoInprepay'},
    ChargePerAdjRef:{label :'ChargePerAdjRef'},
    NextCutoffDate:{label :'NextCutoffDate'},
    LastCutoffDate:{label :'LastCutoffDate'},
    LastChargeDate:{label :'LastChargeDate'},
    LastNoticeDate:{label :'LastNoticeDate'},
    NotBillMedium:{label :'NotBillMedium'},
    ChargeStartDate:{label :'ChargeStartDate'},
    EarliestEndDate:{label :'EarliestEndDate'},
    CommonRefDataInd:{label :'CommonRefDataInd'},
    ContractLanguage:{label :'ContractLanguage'},
    PendingLanguage:{label :'PendingLanguage'},
    RrCandidate:{label :'RrCandidate'},
    ChStatusValidfrom:{label :'ChStatusValidfrom'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteContractAll(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
