/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'OrdertrailerDelete',
    Heading:'Ordertrailer',
    Otxact:{label :'Otxact'},
    Otseq:{label :'Otseq'},
    Otmeas:{label :'Otmeas'},
    Otum:{label :'Otum'},
    Otup:{label :'Otup'},
    Otqord:{label :'Otqord'},
    Otqbkord:{label :'Otqbkord'},
    Otqtoshp:{label :'Otqtoshp'},
    Otdftprc:{label :'Otdftprc'},
    Otprgroup:{label :'Otprgroup'},
    Otfrtwgt:{label :'Otfrtwgt'},
    Otjobcost:{label :'Otjobcost'},
    Otname:{label :'Otname'},
    Otglsale:{label :'Otglsale'},
    Otglcogs:{label :'Otglcogs'},
    Otglinv:{label :'Otglinv'},
    Otqship:{label :'Otqship'},
    Otprmeas:{label :'Otprmeas'},
    Otprum:{label :'Otprum'},
    Otbillunits:{label :'Otbillunits'},
    Otinvunits:{label :'Otinvunits'},
    Otcostflg:{label :'Otcostflg'},
    Otinvalloc:{label :'Otinvalloc'},
    Otshipdate:{label :'Otshipdate'},
    Sncode:{label :'Sncode'},
    OteqId:{label :'OteqId'},
    Oteqrate:{label :'Oteqrate'},
    Otleasing:{label :'Otleasing'},
    OtleasFinish:{label :'OtleasFinish'},
    Otflsqn:{label :'Otflsqn'},
    Otvplmn:{label :'Otvplmn'},
    Otflname:{label :'Otflname'},
    Otfct:{label :'Otfct'},
    Otlct:{label :'Otlct'},
    OtsimFrom:{label :'OtsimFrom'},
    OtsimTo:{label :'OtsimTo'},
    OttransactionDate:{label :'OttransactionDate'},
    ServcatCode:{label :'ServcatCode'},
    ServCode:{label :'ServCode'},
    ServType:{label :'ServType'},
    TaxInclusiveInd:{label :'TaxInclusiveInd'},
    OtglDisc:{label :'OtglDisc'},
    OtjcidDisc:{label :'OtjcidDisc'},
    OtglMincom:{label :'OtglMincom'},
    OtjcidMincom:{label :'OtjcidMincom'},
    GlCurrency:{label :'GlCurrency'},
    DocumentCurrency:{label :'DocumentCurrency'},
    OtamtDiscGl:{label :'OtamtDiscGl'},
    OtamtDiscGrossGl:{label :'OtamtDiscGrossGl'},
    OtamtMincomGl:{label :'OtamtMincomGl'},
    OtamtMincomGrossGl:{label :'OtamtMincomGrossGl'},
    OtamtRevenueGl:{label :'OtamtRevenueGl'},
    OtamtRevenueGrossGl:{label :'OtamtRevenueGrossGl'},
    OtcuramtDiscGl:{label :'OtcuramtDiscGl'},
    OtcuramtDiscGrossGl:{label :'OtcuramtDiscGrossGl'},
    OtcuramtGl:{label :'OtcuramtGl'},
    OtcuramtGrossGl:{label :'OtcuramtGrossGl'},
    OtcuramtMincomGl:{label :'OtcuramtMincomGl'},
    OtcuramtMincomGrossGl:{label :'OtcuramtMincomGrossGl'},
    OtcuramtRevenueGl:{label :'OtcuramtRevenueGl'},
    OtcuramtRevenueGrossGl:{label :'OtcuramtRevenueGrossGl'},
    OtmerchGl:{label :'OtmerchGl'},
    OtmerchGrossGl:{label :'OtmerchGrossGl'},
    OtamtDiscDoc:{label :'OtamtDiscDoc'},
    OtamtDiscGrossDoc:{label :'OtamtDiscGrossDoc'},
    OtamtMincomDoc:{label :'OtamtMincomDoc'},
    OtamtMincomGrossDoc:{label :'OtamtMincomGrossDoc'},
    OtamtRevenueDoc:{label :'OtamtRevenueDoc'},
    OtamtRevenueGrossDoc:{label :'OtamtRevenueGrossDoc'},
    OtcuramtDiscDoc:{label :'OtcuramtDiscDoc'},
    OtcuramtDiscGrossDoc:{label :'OtcuramtDiscGrossDoc'},
    OtcuramtDoc:{label :'OtcuramtDoc'},
    OtcuramtGrossDoc:{label :'OtcuramtGrossDoc'},
    OtcuramtMincomDoc:{label :'OtcuramtMincomDoc'},
    OtcuramtMincomGrossDoc:{label :'OtcuramtMincomGrossDoc'},
    OtcuramtRevenueDoc:{label :'OtcuramtRevenueDoc'},
    OtcuramtRevenueGrossDoc:{label :'OtcuramtRevenueGrossDoc'},
    OtgpriceDisDoc:{label :'OtgpriceDisDoc'},
    OtgpriceDoc:{label :'OtgpriceDoc'},
    OtmerchDoc:{label :'OtmerchDoc'},
    OtmerchGrossDoc:{label :'OtmerchGrossDoc'},
    OttaxExemptedDoc:{label :'OttaxExemptedDoc'},
    RecVersion:{label :'RecVersion'},
    OtamtDiscSecdoc:{label :'OtamtDiscSecdoc'},
    OtamtDiscGrossSecdoc:{label :'OtamtDiscGrossSecdoc'},
    OtamtMincomSecdoc:{label :'OtamtMincomSecdoc'},
    OtamtMincomGrossSecdoc:{label :'OtamtMincomGrossSecdoc'},
    OtamtRevenueSecdoc:{label :'OtamtRevenueSecdoc'},
    OtamtRevenueGrossSecdoc:{label :'OtamtRevenueGrossSecdoc'},
    OtgpriceSecdoc:{label :'OtgpriceSecdoc'},
    OtgpriceDisSecdoc:{label :'OtgpriceDisSecdoc'},
    OtmerchSecdoc:{label :'OtmerchSecdoc'},
    OtmerchGrossSecdoc:{label :'OtmerchGrossSecdoc'},
    Otflrapflg:{label :'Otflrapflg'},
    TapRefNo:{label :'TapRefNo'},
    TaxCalculationType:{label :'TaxCalculationType'},
    ProfileId:{label :'ProfileId'},
    PaymentOption:{label :'PaymentOption'},
    BpCoId:{label :'BpCoId'},
    Otcostcent:{label :'Otcostcent'},
    Otordnum:{label :'Otordnum'},
    IncomingDocTaxItemSeqno:{label :'IncomingDocTaxItemSeqno'},
    Tmcode:{label :'Tmcode'},
    RateplanVscode:{label :'RateplanVscode'},
    Spcode:{label :'Spcode'},
    InvoiceItemClassId:{label :'InvoiceItemClassId'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteOrdertrailer(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
