/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ContractHistoryNew',
    Heading:'ContractHistory',
    CoId:{label :'CoId'},
    ChSeqno:{label :'ChSeqno'},
    ChStatus:{label :'ChStatus'},
    ChReason:{label :'ChReason'},
    ChValidfrom:{label :'ChValidfrom'},
    ChPending:{label :'ChPending'},
    Entdate:{label :'Entdate'},
    Userlastmod:{label :'Userlastmod'},
    Request:{label :'Request'},
    RecVersion:{label :'RecVersion'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{coId:'',
        chSeqno:'',
        chStatus:'',
        chReason:'',
        chValidfrom:'',
        chPending:'',
        entdate:'',
        userlastmod:'',
        request:'',
        recVersion:'',
        }
    }
    res.render('ContractHistoryNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newContractHistory(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('ContractHistoryNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
