/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'DirectoryNumberNew',
    Heading:'DirectoryNumber',
    DnId:{label :'DnId'},
    Plcode:{label :'Plcode'},
    Ndc:{label :'Ndc'},
    Hlcode:{label :'Hlcode'},
    DnNum:{label :'DnNum'},
    DnStatus:{label :'DnStatus'},
    DnStatusModDate:{label :'DnStatusModDate'},
    DealerId:{label :'DealerId'},
    DnAssignDate:{label :'DnAssignDate'},
    DnPhoneFlag:{label :'DnPhoneFlag'},
    DnType:{label :'DnType'},
    DnStatusRequ:{label :'DnStatusRequ'},
    DnStaRequDate:{label :'DnStaRequDate'},
    DnAssign:{label :'DnAssign'},
    DnEntdate:{label :'DnEntdate'},
    DnModdate:{label :'DnModdate'},
    DnModflag:{label :'DnModflag'},
    DnAuth:{label :'DnAuth'},
    Evcode:{label :'Evcode'},
    Hmcode:{label :'Hmcode'},
    LocalPrefixLen:{label :'LocalPrefixLen'},
    SimpohId:{label :'SimpohId'},
    SimpotId:{label :'SimpotId'},
    SimpotBatch:{label :'SimpotBatch'},
    ExternalInd:{label :'ExternalInd'},
    BlockInd:{label :'BlockInd'},
    ExtensionLengthMax:{label :'ExtensionLengthMax'},
    DnAuthPending:{label :'DnAuthPending'},
    RecVersion:{label :'RecVersion'},
    DirnumNpcode:{label :'DirnumNpcode'},
    VpnId:{label :'VpnId'},
    StaticPdpRequired:{label :'StaticPdpRequired'},
    RoamingAllowed:{label :'RoamingAllowed'},
    TransactionId:{label :'TransactionId'},
    BusinessUnitId:{label :'BusinessUnitId'},
    ReservedForPortingInd:{label :'ReservedForPortingInd'},
    PortedNumberInd:{label :'PortedNumberInd'},
    Rscode:{label :'Rscode'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{dnId:'',
        plcode:'',
        ndc:'',
        hlcode:'',
        dnNum:'',
        dnStatus:'',
        dnStatusModDate:'',
        dealerId:'',
        dnAssignDate:'',
        dnPhoneFlag:'',
        dnType:'',
        dnStatusRequ:'',
        dnStaRequDate:'',
        dnAssign:'',
        dnEntdate:'',
        dnModdate:'',
        dnModflag:'',
        dnAuth:'',
        evcode:'',
        hmcode:'',
        localPrefixLen:'',
        simpohId:'',
        simpotId:'',
        simpotBatch:'',
        externalInd:'',
        blockInd:'',
        extensionLengthMax:'',
        dnAuthPending:'',
        recVersion:'',
        dirnumNpcode:'',
        vpnId:'',
        staticPdpRequired:'',
        roamingAllowed:'',
        transactionId:'',
        businessUnitId:'',
        reservedForPortingInd:'',
        portedNumberInd:'',
        rscode:'',
        }
    }
    res.render('DirectoryNumberNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newDirectoryNumber(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('DirectoryNumberNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
