/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'InfoCustComboNew',
    Heading:'InfoCustCombo',
    CustomerId:{label :'CustomerId'},
    Combo01:{label :'Combo01'},
    Combo02:{label :'Combo02'},
    Combo03:{label :'Combo03'},
    Combo04:{label :'Combo04'},
    Combo05:{label :'Combo05'},
    Combo06:{label :'Combo06'},
    Combo07:{label :'Combo07'},
    Combo08:{label :'Combo08'},
    Combo09:{label :'Combo09'},
    Combo10:{label :'Combo10'},
    Combo11:{label :'Combo11'},
    Combo12:{label :'Combo12'},
    Combo13:{label :'Combo13'},
    Combo14:{label :'Combo14'},
    Combo15:{label :'Combo15'},
    Combo16:{label :'Combo16'},
    Combo17:{label :'Combo17'},
    Combo18:{label :'Combo18'},
    Combo19:{label :'Combo19'},
    Combo20:{label :'Combo20'},
    RecVersion:{label :'RecVersion'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{customerId:'',
        combo01:'',
        combo02:'',
        combo03:'',
        combo04:'',
        combo05:'',
        combo06:'',
        combo07:'',
        combo08:'',
        combo09:'',
        combo10:'',
        combo11:'',
        combo12:'',
        combo13:'',
        combo14:'',
        combo15:'',
        combo16:'',
        combo17:'',
        combo18:'',
        combo19:'',
        combo20:'',
        recVersion:'',
        }
    }
    res.render('InfoCustComboNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newInfoCustCombo(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('InfoCustComboNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
