/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ProfileServiceNew',
    Heading:'ProfileService',
    ProfileId:{label :'ProfileId'},
    CoId:{label :'CoId'},
    Sncode:{label :'Sncode'},
    SpcodeHistno:{label :'SpcodeHistno'},
    StatusHistno:{label :'StatusHistno'},
    EntryDate:{label :'EntryDate'},
    ChannelNum:{label :'ChannelNum'},
    OvwAccFirst:{label :'OvwAccFirst'},
    DateBilled:{label :'DateBilled'},
    SnClass:{label :'SnClass'},
    OvwSubscr:{label :'OvwSubscr'},
    Subscript:{label :'Subscript'},
    OvwAccess:{label :'OvwAccess'},
    OvwAccPrd:{label :'OvwAccPrd'},
    Accessfee:{label :'Accessfee'},
    ChannelExcl:{label :'ChannelExcl'},
    DisSubscr:{label :'DisSubscr'},
    InstallDate:{label :'InstallDate'},
    TrialEndDate:{label :'TrialEndDate'},
    PrmValueId:{label :'PrmValueId'},
    Currency:{label :'Currency'},
    SrvType:{label :'SrvType'},
    SrvSubtype:{label :'SrvSubtype'},
    OvwAdvCharge:{label :'OvwAdvCharge'},
    AdvCharge:{label :'AdvCharge'},
    AdvChargePrd:{label :'AdvChargePrd'},
    DeleteFlag:{label :'DeleteFlag'},
    RecVersion:{label :'RecVersion'},
    AttribHistno:{label :'AttribHistno'},
    AttribHistnoNnp:{label :'AttribHistnoNnp'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{profileId:'',
        coId:'',
        sncode:'',
        spcodeHistno:'',
        statusHistno:'',
        entryDate:'',
        channelNum:'',
        ovwAccFirst:'',
        dateBilled:'',
        snClass:'',
        ovwSubscr:'',
        subscript:'',
        ovwAccess:'',
        ovwAccPrd:'',
        accessfee:'',
        channelExcl:'',
        disSubscr:'',
        installDate:'',
        trialEndDate:'',
        prmValueId:'',
        currency:'',
        srvType:'',
        srvSubtype:'',
        ovwAdvCharge:'',
        advCharge:'',
        advChargePrd:'',
        deleteFlag:'',
        recVersion:'',
        attribHistno:'',
        attribHistnoNnp:'',
        }
    }
    res.render('ProfileServiceNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newProfileService(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('ProfileServiceNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
