/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ContractHistoryRead',
    Heading:'ContractHistory',
    CoId:{label :'CoId'},
    ChSeqno:{label :'ChSeqno'},
    ChStatus:{label :'ChStatus'},
    ChReason:{label :'ChReason'},
    ChValidfrom:{label :'ChValidfrom'},
    ChPending:{label :'ChPending'},
    Entdate:{label :'Entdate'},
    Userlastmod:{label :'Userlastmod'},
    Request:{label :'Request'},
    RecVersion:{label :'RecVersion'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readContractHistory?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readContractHistory = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readContractHistory(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchContractHistory');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('ContractHistoryReadPage',parameter);
    }    
    Promise.all([readContractHistory]).then(sendResult);
});

module.exports = router;
