/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'InfoContrComboRead',
    Heading:'InfoContrCombo',
    CoId:{label :'CoId'},
    Combo01:{label :'Combo01'},
    Combo02:{label :'Combo02'},
    Combo03:{label :'Combo03'},
    Combo04:{label :'Combo04'},
    Combo05:{label :'Combo05'},
    Combo06:{label :'Combo06'},
    Combo07:{label :'Combo07'},
    Combo08:{label :'Combo08'},
    Combo09:{label :'Combo09'},
    Combo10:{label :'Combo10'},
    Combo11:{label :'Combo11'},
    Combo12:{label :'Combo12'},
    Combo13:{label :'Combo13'},
    Combo14:{label :'Combo14'},
    Combo15:{label :'Combo15'},
    Combo16:{label :'Combo16'},
    Combo17:{label :'Combo17'},
    Combo18:{label :'Combo18'},
    Combo19:{label :'Combo19'},
    Combo20:{label :'Combo20'},
    RecVersion:{label :'RecVersion'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readInfoContrCombo?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readInfoContrCombo = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readInfoContrCombo(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchInfoContrCombo');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('InfoContrComboReadPage',parameter);
    }    
    Promise.all([readInfoContrCombo]).then(sendResult);
});

module.exports = router;
