/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'InfoContrComboSearch',
    Heading:'InfoContrCombo',
    CoId:{label :'CoId'},
    Combo01:{label :'Combo01'},
    Combo02:{label :'Combo02'},
    Combo03:{label :'Combo03'},
    Combo04:{label :'Combo04'},
    Combo05:{label :'Combo05'},
    Combo06:{label :'Combo06'},
    Combo07:{label :'Combo07'},
    Combo08:{label :'Combo08'},
    Combo09:{label :'Combo09'},
    Combo10:{label :'Combo10'},
    Combo11:{label :'Combo11'},
    Combo12:{label :'Combo12'},
    Combo13:{label :'Combo13'},
    Combo14:{label :'Combo14'},
    Combo15:{label :'Combo15'},
    Combo16:{label :'Combo16'},
    Combo17:{label :'Combo17'},
    Combo18:{label :'Combo18'},
    Combo19:{label :'Combo19'},
    Combo20:{label :'Combo20'},
    RecVersion:{label :'RecVersion'},
    InfoContrCombo:{Heading:'InfoContrCombo',
        CoId:{header:'CoId'},
        Combo01:{header:'Combo01'},
        Combo02:{header:'Combo02'},
        Combo03:{header:'Combo03'},
        Combo04:{header:'Combo04'},
        Combo05:{header:'Combo05'},
        Combo06:{header:'Combo06'},
        Combo07:{header:'Combo07'},
        Combo08:{header:'Combo08'},
        Combo09:{header:'Combo09'},
        Combo10:{header:'Combo10'},
        Combo11:{header:'Combo11'},
        Combo12:{header:'Combo12'},
        Combo13:{header:'Combo13'},
        Combo14:{header:'Combo14'},
        Combo15:{header:'Combo15'},
        Combo16:{header:'Combo16'},
        Combo17:{header:'Combo17'},
        Combo18:{header:'Combo18'},
        Combo19:{header:'Combo19'},
        Combo20:{header:'Combo20'},
        RecVersion:{header:'RecVersion'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchInfoContrCombo?'+req._parsedUrl.query;
    dao.searchInfoContrCombo(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('InfoContrComboSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
