/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ContrServicesCapSearch',
    Heading:'ContrServicesCap',
    CoId:{label :'CoId'},
    Sncode:{label :'Sncode'},
    Seqno:{label :'Seqno'},
    SeqnoPre:{label :'SeqnoPre'},
    Bccode:{label :'Bccode'},
    PendingBccode:{label :'PendingBccode'},
    DnId:{label :'DnId'},
    DnBlockId:{label :'DnBlockId'},
    MainDirnum:{label :'MainDirnum'},
    CsStatus:{label :'CsStatus'},
    CsActivDate:{label :'CsActivDate'},
    CsDeactivDate:{label :'CsDeactivDate'},
    CsRequest:{label :'CsRequest'},
    RecVersion:{label :'RecVersion'},
    PublicNumberDnId:{label :'PublicNumberDnId'},
    VpnId:{label :'VpnId'},
    PublicBlockId:{label :'PublicBlockId'},
    ProfileId:{label :'ProfileId'},
    DnShownInBill:{label :'DnShownInBill'},
    RequestId:{label :'RequestId'},
    ContrServicesCap:{Heading:'ContrServicesCap',
        CoId:{header:'CoId'},
        Sncode:{header:'Sncode'},
        Seqno:{header:'Seqno'},
        SeqnoPre:{header:'SeqnoPre'},
        Bccode:{header:'Bccode'},
        PendingBccode:{header:'PendingBccode'},
        DnId:{header:'DnId'},
        DnBlockId:{header:'DnBlockId'},
        MainDirnum:{header:'MainDirnum'},
        CsStatus:{header:'CsStatus'},
        CsActivDate:{header:'CsActivDate'},
        CsDeactivDate:{header:'CsDeactivDate'},
        CsRequest:{header:'CsRequest'},
        RecVersion:{header:'RecVersion'},
        PublicNumberDnId:{header:'PublicNumberDnId'},
        VpnId:{header:'VpnId'},
        PublicBlockId:{header:'PublicBlockId'},
        ProfileId:{header:'ProfileId'},
        DnShownInBill:{header:'DnShownInBill'},
        RequestId:{header:'RequestId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchContrServicesCap?'+req._parsedUrl.query;
    dao.searchContrServicesCap(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('ContrServicesCapSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
