/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'PortSearch',
    Heading:'Port',
    PortId:{label :'PortId'},
    Plcode:{label :'Plcode'},
    Hlcode:{label :'Hlcode'},
    PortNum:{label :'PortNum'},
    PortStatus:{label :'PortStatus'},
    PortStatusmoddat:{label :'PortStatusmoddat'},
    PortKi:{label :'PortKi'},
    PortKind:{label :'PortKind'},
    PortChannels:{label :'PortChannels'},
    PortChannelsExcl:{label :'PortChannelsExcl'},
    SmId:{label :'SmId'},
    PortSmRequ:{label :'PortSmRequ'},
    SimpohId:{label :'SimpohId'},
    SimpotId:{label :'SimpotId'},
    SimpotBatch:{label :'SimpotBatch'},
    DnId:{label :'DnId'},
    DealerId:{label :'DealerId'},
    PortAssignDate:{label :'PortAssignDate'},
    PortTkey:{label :'PortTkey'},
    PortStatusRequ:{label :'PortStatusRequ'},
    PortStaRequDate:{label :'PortStaRequDate'},
    PortActivDate:{label :'PortActivDate'},
    PortDeactivDate:{label :'PortDeactivDate'},
    PortEntdate:{label :'PortEntdate'},
    PortModdate:{label :'PortModdate'},
    PortUserlastmod:{label :'PortUserlastmod'},
    PreActivated:{label :'PreActivated'},
    SmsUpdate:{label :'SmsUpdate'},
    PortRicBatch:{label :'PortRicBatch'},
    ExternalInd:{label :'ExternalInd'},
    Capacity:{label :'Capacity'},
    AvailableCapacity:{label :'AvailableCapacity'},
    PrmValueId:{label :'PrmValueId'},
    RecVersion:{label :'RecVersion'},
    PortNpcode:{label :'PortNpcode'},
    TransactionId:{label :'TransactionId'},
    BusinessUnitId:{label :'BusinessUnitId'},
    Port:{Heading:'Port',
        PortId:{header:'PortId'},
        Plcode:{header:'Plcode'},
        Hlcode:{header:'Hlcode'},
        PortNum:{header:'PortNum'},
        PortStatus:{header:'PortStatus'},
        PortStatusmoddat:{header:'PortStatusmoddat'},
        PortKi:{header:'PortKi'},
        PortKind:{header:'PortKind'},
        PortChannels:{header:'PortChannels'},
        PortChannelsExcl:{header:'PortChannelsExcl'},
        SmId:{header:'SmId'},
        PortSmRequ:{header:'PortSmRequ'},
        SimpohId:{header:'SimpohId'},
        SimpotId:{header:'SimpotId'},
        SimpotBatch:{header:'SimpotBatch'},
        DnId:{header:'DnId'},
        DealerId:{header:'DealerId'},
        PortAssignDate:{header:'PortAssignDate'},
        PortTkey:{header:'PortTkey'},
        PortStatusRequ:{header:'PortStatusRequ'},
        PortStaRequDate:{header:'PortStaRequDate'},
        PortActivDate:{header:'PortActivDate'},
        PortDeactivDate:{header:'PortDeactivDate'},
        PortEntdate:{header:'PortEntdate'},
        PortModdate:{header:'PortModdate'},
        PortUserlastmod:{header:'PortUserlastmod'},
        PreActivated:{header:'PreActivated'},
        SmsUpdate:{header:'SmsUpdate'},
        PortRicBatch:{header:'PortRicBatch'},
        ExternalInd:{header:'ExternalInd'},
        Capacity:{header:'Capacity'},
        AvailableCapacity:{header:'AvailableCapacity'},
        PrmValueId:{header:'PrmValueId'},
        RecVersion:{header:'RecVersion'},
        PortNpcode:{header:'PortNpcode'},
        TransactionId:{header:'TransactionId'},
        BusinessUnitId:{header:'BusinessUnitId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchPort?'+req._parsedUrl.query;
    dao.searchPort(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('PortSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
