/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'InfoCustTextSearch',
    Heading:'InfoCustText',
    CustomerId:{label :'CustomerId'},
    Text01:{label :'Text01'},
    Text02:{label :'Text02'},
    Text03:{label :'Text03'},
    Text04:{label :'Text04'},
    Text05:{label :'Text05'},
    Text06:{label :'Text06'},
    Text07:{label :'Text07'},
    Text08:{label :'Text08'},
    Text09:{label :'Text09'},
    Text10:{label :'Text10'},
    Text11:{label :'Text11'},
    Text12:{label :'Text12'},
    Text13:{label :'Text13'},
    Text14:{label :'Text14'},
    Text15:{label :'Text15'},
    Text16:{label :'Text16'},
    Text17:{label :'Text17'},
    Text18:{label :'Text18'},
    Text19:{label :'Text19'},
    Text20:{label :'Text20'},
    Text21:{label :'Text21'},
    Text22:{label :'Text22'},
    Text23:{label :'Text23'},
    Text24:{label :'Text24'},
    Text25:{label :'Text25'},
    Text26:{label :'Text26'},
    Text27:{label :'Text27'},
    Text28:{label :'Text28'},
    Text29:{label :'Text29'},
    Text30:{label :'Text30'},
    RecVersion:{label :'RecVersion'},
    InfoCustText:{Heading:'InfoCustText',
        CustomerId:{header:'CustomerId'},
        Text01:{header:'Text01'},
        Text02:{header:'Text02'},
        Text03:{header:'Text03'},
        Text04:{header:'Text04'},
        Text05:{header:'Text05'},
        Text06:{header:'Text06'},
        Text07:{header:'Text07'},
        Text08:{header:'Text08'},
        Text09:{header:'Text09'},
        Text10:{header:'Text10'},
        Text11:{header:'Text11'},
        Text12:{header:'Text12'},
        Text13:{header:'Text13'},
        Text14:{header:'Text14'},
        Text15:{header:'Text15'},
        Text16:{header:'Text16'},
        Text17:{header:'Text17'},
        Text18:{header:'Text18'},
        Text19:{header:'Text19'},
        Text20:{header:'Text20'},
        Text21:{header:'Text21'},
        Text22:{header:'Text22'},
        Text23:{header:'Text23'},
        Text24:{header:'Text24'},
        Text25:{header:'Text25'},
        Text26:{header:'Text26'},
        Text27:{header:'Text27'},
        Text28:{header:'Text28'},
        Text29:{header:'Text29'},
        Text30:{header:'Text30'},
        RecVersion:{header:'RecVersion'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchInfoCustText?'+req._parsedUrl.query;
    dao.searchInfoCustText(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('InfoCustTextSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
