/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ContractHistorySearch',
    Heading:'ContractHistory',
    CoId:{label :'CoId'},
    ChSeqno:{label :'ChSeqno'},
    ChStatus:{label :'ChStatus'},
    ChReason:{label :'ChReason'},
    ChValidfrom:{label :'ChValidfrom'},
    ChPending:{label :'ChPending'},
    Entdate:{label :'Entdate'},
    Userlastmod:{label :'Userlastmod'},
    Request:{label :'Request'},
    RecVersion:{label :'RecVersion'},
    ContractHistory:{Heading:'ContractHistory',
        CoId:{header:'CoId'},
        ChSeqno:{header:'ChSeqno'},
        ChStatus:{header:'ChStatus'},
        ChReason:{header:'ChReason'},
        ChValidfrom:{header:'ChValidfrom'},
        ChPending:{header:'ChPending'},
        Entdate:{header:'Entdate'},
        Userlastmod:{header:'Userlastmod'},
        Request:{header:'Request'},
        RecVersion:{header:'RecVersion'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchContractHistory?'+req._parsedUrl.query;
    dao.searchContractHistory(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('ContractHistorySearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
