/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'PrServSpcodeHistSearch',
    Heading:'PrServSpcodeHist',
    ProfileId:{label :'ProfileId'},
    CoId:{label :'CoId'},
    Sncode:{label :'Sncode'},
    Histno:{label :'Histno'},
    Spcode:{label :'Spcode'},
    Transactionno:{label :'Transactionno'},
    ValidFromDate:{label :'ValidFromDate'},
    EntryDate:{label :'EntryDate'},
    RequestId:{label :'RequestId'},
    RecVersion:{label :'RecVersion'},
    PrServSpcodeHist:{Heading:'PrServSpcodeHist',
        ProfileId:{header:'ProfileId'},
        CoId:{header:'CoId'},
        Sncode:{header:'Sncode'},
        Histno:{header:'Histno'},
        Spcode:{header:'Spcode'},
        Transactionno:{header:'Transactionno'},
        ValidFromDate:{header:'ValidFromDate'},
        EntryDate:{header:'EntryDate'},
        RequestId:{header:'RequestId'},
        RecVersion:{header:'RecVersion'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchPrServSpcodeHist?'+req._parsedUrl.query;
    dao.searchPrServSpcodeHist(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('PrServSpcodeHistSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
