/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ProfileServiceSearch',
    Heading:'ProfileService',
    ProfileId:{label :'ProfileId'},
    CoId:{label :'CoId'},
    Sncode:{label :'Sncode'},
    SpcodeHistno:{label :'SpcodeHistno'},
    StatusHistno:{label :'StatusHistno'},
    EntryDate:{label :'EntryDate'},
    ChannelNum:{label :'ChannelNum'},
    OvwAccFirst:{label :'OvwAccFirst'},
    DateBilled:{label :'DateBilled'},
    SnClass:{label :'SnClass'},
    OvwSubscr:{label :'OvwSubscr'},
    Subscript:{label :'Subscript'},
    OvwAccess:{label :'OvwAccess'},
    OvwAccPrd:{label :'OvwAccPrd'},
    Accessfee:{label :'Accessfee'},
    ChannelExcl:{label :'ChannelExcl'},
    DisSubscr:{label :'DisSubscr'},
    InstallDate:{label :'InstallDate'},
    TrialEndDate:{label :'TrialEndDate'},
    PrmValueId:{label :'PrmValueId'},
    Currency:{label :'Currency'},
    SrvType:{label :'SrvType'},
    SrvSubtype:{label :'SrvSubtype'},
    OvwAdvCharge:{label :'OvwAdvCharge'},
    AdvCharge:{label :'AdvCharge'},
    AdvChargePrd:{label :'AdvChargePrd'},
    DeleteFlag:{label :'DeleteFlag'},
    RecVersion:{label :'RecVersion'},
    AttribHistno:{label :'AttribHistno'},
    AttribHistnoNnp:{label :'AttribHistnoNnp'},
    ProfileService:{Heading:'ProfileService',
        ProfileId:{header:'ProfileId'},
        CoId:{header:'CoId'},
        Sncode:{header:'Sncode'},
        SpcodeHistno:{header:'SpcodeHistno'},
        StatusHistno:{header:'StatusHistno'},
        EntryDate:{header:'EntryDate'},
        ChannelNum:{header:'ChannelNum'},
        OvwAccFirst:{header:'OvwAccFirst'},
        DateBilled:{header:'DateBilled'},
        SnClass:{header:'SnClass'},
        OvwSubscr:{header:'OvwSubscr'},
        Subscript:{header:'Subscript'},
        OvwAccess:{header:'OvwAccess'},
        OvwAccPrd:{header:'OvwAccPrd'},
        Accessfee:{header:'Accessfee'},
        ChannelExcl:{header:'ChannelExcl'},
        DisSubscr:{header:'DisSubscr'},
        InstallDate:{header:'InstallDate'},
        TrialEndDate:{header:'TrialEndDate'},
        PrmValueId:{header:'PrmValueId'},
        Currency:{header:'Currency'},
        SrvType:{header:'SrvType'},
        SrvSubtype:{header:'SrvSubtype'},
        OvwAdvCharge:{header:'OvwAdvCharge'},
        AdvCharge:{header:'AdvCharge'},
        AdvChargePrd:{header:'AdvChargePrd'},
        DeleteFlag:{header:'DeleteFlag'},
        RecVersion:{header:'RecVersion'},
        AttribHistno:{header:'AttribHistno'},
        AttribHistnoNnp:{header:'AttribHistnoNnp'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchProfileService?'+req._parsedUrl.query;
    dao.searchProfileService(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('ProfileServiceSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
