/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ContrDevicesSearch',
    Heading:'ContrDevices',
    CdId:{label :'CdId'},
    CdSeqno:{label :'CdSeqno'},
    CoId:{label :'CoId'},
    PortId:{label :'PortId'},
    DnId:{label :'DnId'},
    EqId:{label :'EqId'},
    CdStatus:{label :'CdStatus'},
    CdActivDate:{label :'CdActivDate'},
    CdDeactivDate:{label :'CdDeactivDate'},
    CdValidfrom:{label :'CdValidfrom'},
    CdEntdate:{label :'CdEntdate'},
    CdModdate:{label :'CdModdate'},
    CdUserlastmod:{label :'CdUserlastmod'},
    CdSmNum:{label :'CdSmNum'},
    CdChannels:{label :'CdChannels'},
    CdChannelsExcl:{label :'CdChannelsExcl'},
    CdEqNum:{label :'CdEqNum'},
    CdPendingState:{label :'CdPendingState'},
    CdRsId:{label :'CdRsId'},
    CdPlcode:{label :'CdPlcode'},
    Hlcode:{label :'Hlcode'},
    RecVersion:{label :'RecVersion'},
    ContrDevices:{Heading:'ContrDevices',
        CdId:{header:'CdId'},
        CdSeqno:{header:'CdSeqno'},
        CoId:{header:'CoId'},
        PortId:{header:'PortId'},
        DnId:{header:'DnId'},
        EqId:{header:'EqId'},
        CdStatus:{header:'CdStatus'},
        CdActivDate:{header:'CdActivDate'},
        CdDeactivDate:{header:'CdDeactivDate'},
        CdValidfrom:{header:'CdValidfrom'},
        CdEntdate:{header:'CdEntdate'},
        CdModdate:{header:'CdModdate'},
        CdUserlastmod:{header:'CdUserlastmod'},
        CdSmNum:{header:'CdSmNum'},
        CdChannels:{header:'CdChannels'},
        CdChannelsExcl:{header:'CdChannelsExcl'},
        CdEqNum:{header:'CdEqNum'},
        CdPendingState:{header:'CdPendingState'},
        CdRsId:{header:'CdRsId'},
        CdPlcode:{header:'CdPlcode'},
        Hlcode:{header:'Hlcode'},
        RecVersion:{header:'RecVersion'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchContrDevices?'+req._parsedUrl.query;
    dao.searchContrDevices(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('ContrDevicesSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
