/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'DirectoryNumberSearch',
    Heading:'DirectoryNumber',
    DnId:{label :'DnId'},
    Plcode:{label :'Plcode'},
    Ndc:{label :'Ndc'},
    Hlcode:{label :'Hlcode'},
    DnNum:{label :'DnNum'},
    DnStatus:{label :'DnStatus'},
    DnStatusModDate:{label :'DnStatusModDate'},
    DealerId:{label :'DealerId'},
    DnAssignDate:{label :'DnAssignDate'},
    DnPhoneFlag:{label :'DnPhoneFlag'},
    DnType:{label :'DnType'},
    DnStatusRequ:{label :'DnStatusRequ'},
    DnStaRequDate:{label :'DnStaRequDate'},
    DnAssign:{label :'DnAssign'},
    DnEntdate:{label :'DnEntdate'},
    DnModdate:{label :'DnModdate'},
    DnModflag:{label :'DnModflag'},
    DnAuth:{label :'DnAuth'},
    Evcode:{label :'Evcode'},
    Hmcode:{label :'Hmcode'},
    LocalPrefixLen:{label :'LocalPrefixLen'},
    SimpohId:{label :'SimpohId'},
    SimpotId:{label :'SimpotId'},
    SimpotBatch:{label :'SimpotBatch'},
    ExternalInd:{label :'ExternalInd'},
    BlockInd:{label :'BlockInd'},
    ExtensionLengthMax:{label :'ExtensionLengthMax'},
    DnAuthPending:{label :'DnAuthPending'},
    RecVersion:{label :'RecVersion'},
    DirnumNpcode:{label :'DirnumNpcode'},
    VpnId:{label :'VpnId'},
    StaticPdpRequired:{label :'StaticPdpRequired'},
    RoamingAllowed:{label :'RoamingAllowed'},
    TransactionId:{label :'TransactionId'},
    BusinessUnitId:{label :'BusinessUnitId'},
    ReservedForPortingInd:{label :'ReservedForPortingInd'},
    PortedNumberInd:{label :'PortedNumberInd'},
    Rscode:{label :'Rscode'},
    DirectoryNumber:{Heading:'DirectoryNumber',
        DnId:{header:'DnId'},
        Plcode:{header:'Plcode'},
        Ndc:{header:'Ndc'},
        Hlcode:{header:'Hlcode'},
        DnNum:{header:'DnNum'},
        DnStatus:{header:'DnStatus'},
        DnStatusModDate:{header:'DnStatusModDate'},
        DealerId:{header:'DealerId'},
        DnAssignDate:{header:'DnAssignDate'},
        DnPhoneFlag:{header:'DnPhoneFlag'},
        DnType:{header:'DnType'},
        DnStatusRequ:{header:'DnStatusRequ'},
        DnStaRequDate:{header:'DnStaRequDate'},
        DnAssign:{header:'DnAssign'},
        DnEntdate:{header:'DnEntdate'},
        DnModdate:{header:'DnModdate'},
        DnModflag:{header:'DnModflag'},
        DnAuth:{header:'DnAuth'},
        Evcode:{header:'Evcode'},
        Hmcode:{header:'Hmcode'},
        LocalPrefixLen:{header:'LocalPrefixLen'},
        SimpohId:{header:'SimpohId'},
        SimpotId:{header:'SimpotId'},
        SimpotBatch:{header:'SimpotBatch'},
        ExternalInd:{header:'ExternalInd'},
        BlockInd:{header:'BlockInd'},
        ExtensionLengthMax:{header:'ExtensionLengthMax'},
        DnAuthPending:{header:'DnAuthPending'},
        RecVersion:{header:'RecVersion'},
        DirnumNpcode:{header:'DirnumNpcode'},
        VpnId:{header:'VpnId'},
        StaticPdpRequired:{header:'StaticPdpRequired'},
        RoamingAllowed:{header:'RoamingAllowed'},
        TransactionId:{header:'TransactionId'},
        BusinessUnitId:{header:'BusinessUnitId'},
        ReservedForPortingInd:{header:'ReservedForPortingInd'},
        PortedNumberInd:{header:'PortedNumberInd'},
        Rscode:{header:'Rscode'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchDirectoryNumber?'+req._parsedUrl.query;
    dao.searchDirectoryNumber(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('DirectoryNumberSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
