/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'StorageMediumWrite',
    Heading:'StorageMedium',
    SmId:{label :'SmId'},
    Plcode:{label :'Plcode'},
    SmcId:{label :'SmcId'},
    SmSerialnum:{label :'SmSerialnum'},
    SmStatus:{label :'SmStatus'},
    SmStatusModDate:{label :'SmStatusModDate'},
    DealerId:{label :'DealerId'},
    SmDeliveryId:{label :'SmDeliveryId'},
    SmDeliveryDate:{label :'SmDeliveryDate'},
    SimpohId:{label :'SimpohId'},
    SimpotId:{label :'SimpotId'},
    SimpotBatch:{label :'SimpotBatch'},
    SmPin:{label :'SmPin'},
    SmPuk:{label :'SmPuk'},
    SmAccControl:{label :'SmAccControl'},
    SmCodeAdm:{label :'SmCodeAdm'},
    SpIdE:{label :'SpIdE'},
    SpIdG:{label :'SpIdG'},
    SmStatusRequ:{label :'SmStatusRequ'},
    SmStaRequDate:{label :'SmStaRequDate'},
    SmEntdate:{label :'SmEntdate'},
    SmModdate:{label :'SmModdate'},
    SmUserlastmod:{label :'SmUserlastmod'},
    SmPin2:{label :'SmPin2'},
    SmPuk2:{label :'SmPuk2'},
    SmAuth:{label :'SmAuth'},
    PiId:{label :'PiId'},
    ExternalInd:{label :'ExternalInd'},
    Vendcode:{label :'Vendcode'},
    SmAdm1:{label :'SmAdm1'},
    SmAdm2:{label :'SmAdm2'},
    SmAdm3:{label :'SmAdm3'},
    SmAdm4:{label :'SmAdm4'},
    SmCodeRetailer:{label :'SmCodeRetailer'},
    SmCodeA:{label :'SmCodeA'},
    SmCodeB:{label :'SmCodeB'},
    SmAuthPending:{label :'SmAuthPending'},
    RecVersion:{label :'RecVersion'},
    SmOrigEsnId:{label :'SmOrigEsnId'},
    PrepaidProfileId:{label :'PrepaidProfileId'},
    RaProcessId:{label :'RaProcessId'},
    TransactionId:{label :'TransactionId'},
    BusinessUnitId:{label :'BusinessUnitId'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',
    }
    dao.readStorageMedium(jsonObj,function(err,rows) {
        parameter.record = rows[0];
        res.render('StorageMediumWritePage',parameter);
        console.log(parameter);        
    });
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,        
    }
    dao.writeStorageMedium(jsonObj,function(err,rows) {    
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('StorageMediumWritePage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
