/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'CustomerAllWrite',
    Heading:'CustomerAll',
    CustomerId:{label :'CustomerId'},
    CustomerIdHigh:{label :'CustomerIdHigh'},
    Custcode:{label :'Custcode'},
    Csst:{label :'Csst'},
    Cstype:{label :'Cstype'},
    Csactivated:{label :'Csactivated'},
    Csdeactivated:{label :'Csdeactivated'},
    CstypeDate:{label :'CstypeDate'},
    Cslevel:{label :'Cslevel'},
    Cslvlname:{label :'Cslvlname'},
    Tmcode:{label :'Tmcode'},
    Prgcode:{label :'Prgcode'},
    Csclimit:{label :'Csclimit'},
    Cscurbalance:{label :'Cscurbalance'},
    Csdepdate:{label :'Csdepdate'},
    Cstestbillrun:{label :'Cstestbillrun'},
    BillLayout:{label :'BillLayout'},
    Paymntresp:{label :'Paymntresp'},
    TargetReached:{label :'TargetReached'},
    Pcsmethpaymnt:{label :'Pcsmethpaymnt'},
    DunningFlag:{label :'DunningFlag'},
    CommNo:{label :'CommNo'},
    PosCommType:{label :'PosCommType'},
    BtxPassword:{label :'BtxPassword'},
    BtxUser:{label :'BtxUser'},
    SettlesPMonth:{label :'SettlesPMonth'},
    Cashretour:{label :'Cashretour'},
    Cstradecode:{label :'Cstradecode'},
    Cspassword:{label :'Cspassword'},
    Cspromotion:{label :'Cspromotion'},
    Csreason:{label :'Csreason'},
    Cscollector:{label :'Cscollector'},
    Cscontresp:{label :'Cscontresp'},
    Csdeposit:{label :'Csdeposit'},
    CscreditDate:{label :'CscreditDate'},
    CscreditRemark:{label :'CscreditRemark'},
    Suspended:{label :'Suspended'},
    Reactivated:{label :'Reactivated'},
    PrevBalance:{label :'PrevBalance'},
    LbcDate:{label :'LbcDate'},
    CrlimitExc:{label :'CrlimitExc'},
    AreaId:{label :'AreaId'},
    CostcenterId:{label :'CostcenterId'},
    Csfedtaxid:{label :'Csfedtaxid'},
    CreditRating:{label :'CreditRating'},
    CscreditStatus:{label :'CscreditStatus'},
    DeactCreateDate:{label :'DeactCreateDate'},
    DeactReceipDate:{label :'DeactReceipDate'},
    EdifactAddr:{label :'EdifactAddr'},
    EdifactUserFlag:{label :'EdifactUserFlag'},
    EdifactFlag:{label :'EdifactFlag'},
    CsdepositDueDate:{label :'CsdepositDueDate'},
    CalculateDeposit:{label :'CalculateDeposit'},
    TmcodeDate:{label :'TmcodeDate'},
    Csrentalbc:{label :'Csrentalbc'},
    UserLastmod:{label :'UserLastmod'},
    Csentdate:{label :'Csentdate'},
    Csmoddate:{label :'Csmoddate'},
    Csmod:{label :'Csmod'},
    CustomerIdExt:{label :'CustomerIdExt'},
    CsclimitOTr1:{label :'CsclimitOTr1'},
    CsclimitOTr2:{label :'CsclimitOTr2'},
    CsclimitOTr3:{label :'CsclimitOTr3'},
    CscreditScore:{label :'CscreditScore'},
    Cstraderef:{label :'Cstraderef'},
    Wpid:{label :'Wpid'},
    Csprepayment:{label :'Csprepayment'},
    Csremark1:{label :'Csremark1'},
    Csremark2:{label :'Csremark2'},
    BillInformation:{label :'BillInformation'},
    DealerId:{label :'DealerId'},
    DunningMode:{label :'DunningMode'},
    NotValid:{label :'NotValid'},
    CscrdcheckAgreed:{label :'CscrdcheckAgreed'},
    ExpectPayCurrId:{label :'ExpectPayCurrId'},
    ConvratetypePayment:{label :'ConvratetypePayment'},
    RefundCurrId:{label :'RefundCurrId'},
    ConvratetypeRefund:{label :'ConvratetypeRefund'},
    Srcode:{label :'Srcode'},
    Currency:{label :'Currency'},
    RecVersion:{label :'RecVersion'},
    AnonymousCustomer:{label :'AnonymousCustomer'},
    ExternalCustomerId:{label :'ExternalCustomerId'},
    ExternalCustomerSetId:{label :'ExternalCustomerSetId'},
    Custnum:{label :'Custnum'},
    BusinessUnitId:{label :'BusinessUnitId'},
    PartyTypeId:{label :'PartyTypeId'},
    IndividualOverdiscFlag:{label :'IndividualOverdiscFlag'},
    BillingThreshold:{label :'BillingThreshold'},
    BillingThresholdCurrency:{label :'BillingThresholdCurrency'},
    ThresholdBillingMode:{label :'ThresholdBillingMode'},
    ThresholdBillingPurpose:{label :'ThresholdBillingPurpose'},
    CollectionInd:{label :'CollectionInd'},
    RrCandidate:{label :'RrCandidate'},
    BchLastRunDate:{label :'BchLastRunDate'},
    CreatedByUser:{label :'CreatedByUser'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',
    }
    dao.readCustomerAll(jsonObj,function(err,rows) {
        parameter.record = rows[0];
        res.render('CustomerAllWritePage',parameter);
        console.log(parameter);        
    });
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,        
    }
    dao.writeCustomerAll(jsonObj,function(err,rows) {    
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('CustomerAllWritePage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
